[package]
name = "pfin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polling = "2"
libc = "0.2"
getopts = "0.2"

[profile.release]
lto = true
codegen-units = 1
